ALTER TABLE users
ADD COLUMN nombre VARCHAR(100) NOT NULL,
ADD COLUMN email VARCHAR(100) UNIQUE NOT NULL,
ADD COLUMN fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP

ALTER TABLE users 
CHANGE COLUMN nombre fullname VARCHAR(100) NOT NULL;